CREATE TABLE `expansive_control`.TB_AUTHENTICATE_USER(
ID BIGINT auto_increment NOT NULL,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
RF_PROFILE BIGINT NOT NULL,
CONSTRAINT TB_AUTHENTICATE_USER_PK PRIMARY KEY(ID),
CONSTRAINT FK_AUTHENTICATE_USER_PROFILE FOREIGN KEY(RF_PROFILE) REFERENCES TB_PROFILE(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;


