CREATE TABLE `expansive_control`.TB_SIMULATION_AND_OBJECTIVE(
ID BIGINT auto_increment NOT NULL,
OBJECTIVE VARCHAR(255) NOT NULL,
RF_AUTHENTICATE_USER  BIGINT,
CONSTRAINT PK_SIMULATION_AND_OBJECTIVE PRIMARY KEY(ID),
CONSTRAINT FK_SIMULATION_AND_OBJECTIVE_AUTHENTICATE_USER FOREIGN KEY(RF_AUTHENTICATE_USER) REFERENCES TB_AUTHENTICATE_USER(ID)
)ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;