CREATE TABLE `expansive_control`.TB_SIMULATION(
ID BIGINT auto_increment NOT NULL,
NAME VARCHAR(255) NOT NULL,
VALUE  VARCHAR(255) NOT NULL,
RF_SHABBY_TYPE  BIGINT NOT NULL,
DATE_HOUR  DATETIME,
RF_SIMULATION_AND_OBJECTIVE  BIGINT,
CONSTRAINT TB_SIMULATION_PK PRIMARY KEY(ID),
CONSTRAINT FK_SIMULATION_SHABBY_TYPE FOREIGN KEY(RF_SHABBY_TYPE) REFERENCES TB_SHABBY_TYPE(ID),
CONSTRAINT FK_SIMULATION_AND_OBJECTIVE FOREIGN KEY(RF_SIMULATION_AND_OBJECTIVE) REFERENCES TB_SIMULATION_AND_OBJECTIVE(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;


